<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMOJGPj1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMOJGPj1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMOJGPj1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMOJGPj1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMOJGPj1\App_KernelDevDebugContainer([
    'container.build_hash' => 'MOJGPj1',
    'container.build_id' => '4dce7dee',
    'container.build_time' => 1655933697,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMOJGPj1');
