<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerArW78xQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerArW78xQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerArW78xQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerArW78xQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerArW78xQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'ArW78xQ',
    'container.build_id' => '017aab06',
    'container.build_time' => 1652361183,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerArW78xQ');
